In [59]:
# Pascal triangle using numpy
import numpy as np

n = 5 # number of rows of pascal's triangle to compute
    
p_triangle = np.zeros((n, n), dtype = int)
p_triangle[0, 0] = 1
p_triangle[1,0] = p_triangle[1,1] = 1

for n in range(2, n):
    for r in range(0, n+1):
        p_triangle[n, r] = p_triangle[n-1, r-1] + p_triangle[n-1, r]
print(p_triangle)

[[1 0 0 0 0]
 [1 1 0 0 0]
 [1 2 1 0 0]
 [1 3 3 1 0]
 [1 4 6 4 1]]


In [52]:
#pascal triangle using for loops

n = 5
for i in range(1,n+1):
    for j in range(0,n-i+1):
        print(' ',end = ' ')
    c = 1 
    for j in range(1, i+1):
        print('  ', c, sep = '', end =' ')
        c = c* (i-j)//j
    print()

            1 
          1   1 
        1   2   1 
      1   3   3   1 
    1   4   6   4   1 


In [51]:
#pascal triangle using pascal function

from scipy.linalg import pascal
n = 5
pascal = pascal(n,kind='lower')
print(pascal)

[[1 0 0 0 0]
 [1 1 0 0 0]
 [1 2 1 0 0]
 [1 3 3 1 0]
 [1 4 6 4 1]]


In [61]:
# Pascal triangle
n = 10

# iterarte upto n
for i in range(n):
    print(' '*(n-i), end='')
    # compute power of 11
    print(' '.join(map(str, str(11**i))))
    
#11**0 = 1
#11**1 = 11
#11**2 = 121
#11**3 = 1331

          1
         1 1
        1 2 1
       1 3 3 1
      1 4 6 4 1
     1 6 1 0 5 1
    1 7 7 1 5 6 1
   1 9 4 8 7 1 7 1
  2 1 4 3 5 8 8 8 1
 2 3 5 7 9 4 7 6 9 1
